ekf_filter_node:
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: false
  transform_time_offset: 0.0
  print_diagnostics: true

  # Define frames used for transformation
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  # IMU (Witmotion) configuration: Only use orientation and angular velocity
  imu0: /witmotion/imu
  imu0_config: [false, false, false,    # position (ignored)
                true,  true,  true,     # orientation (used)
                false, false, false,    # linear velocity (ignored)
                true,  true,  true,     # angular velocity (used)
                false, false, false]     # bias (ignored)
  imu0_differential: false
  imu0_relative: true
  imu0_queue_size: 10
  imu0_nodelay: false

  # GPS (ublox) configuration: Only use latitude and longitude converted to x/y
  gps0: /ublox/navsat_fix
  gps0_config: [true, true, false,     # latitude, longitude (used)
                false, false, false,   # altitude (ignored)
                false, false, false,   # velocity (ignored)
                false, false, false,   # orientation (ignored)
                false, false, false]   # additional data (ignored)
  gps0_differential: false
  gps0_queue_size: 5
  gps0_nodelay: false