name: Build and push ARM64 Prerequisite Image Daily

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
          cache-binary: true
      
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}
        
      - name: Build & push arm64-prerequisite
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/arm64-prerequisite.Dockerfile
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository }}:arm64-prerequisite
